from __future__ import annotations
import argparse
import asyncio
import logging
import os
import sys
from pathlib import Path
from typing import Any, Optional

import neo4j

from .config import PipelineConfig, load_config
from .llm import get_llm, LLMInterface
from .chunkers import get_chunker
from .extractors import EntityRelationshipExtractor
from .resolvers import EntityResolver
from .writers import GraphRAGNeo4jWriter
from .analyzers import CommunityDetector, CommunitySummarizer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

from .utils import hf_embed
class GraphRAGPipeline:
    def __init__(self, config: PipelineConfig) -> None:
        self.config = config
        self.llm: LLMInterface = get_llm(
            provider=config.llm.provider,
            model=config.llm.model,
            temperature=config.llm.temperature,
            max_tokens=config.llm.max_tokens,
        )
        logger.info("LLM: %s", self.llm)

        self.chunker = get_chunker(
            strategy=config.chunking.strategy,
            chunk_size=config.chunking.chunk_size,
            chunk_overlap=config.chunking.chunk_overlap,
            llm=self.llm
        )
        logger.info("Chunker: %s", self.chunker)

        self._driver = neo4j.GraphDatabase.driver(
            config.neo4j.uri,
            auth=(config.neo4j.user, config.neo4j.password),
        )

        self.writer = GraphRAGNeo4jWriter(
            driver=self._driver,
            database=config.neo4j.database,
        )

        self.er_extractor = EntityRelationshipExtractor(
            llm=self.llm,
            max_concurrency=config.extraction.max_concurrency,
        )

    async def run(self, document_text: str, doc_title: str = "", doc_source: str = "") -> None:
        logger.info("=" * 60)
        logger.info("Starting GraphRAG Pipeline")
        logger.info("=" * 60)

        self.writer.create_indexes()

        doc_id = self.writer.write_document(title=doc_title, source=doc_source)

        logger.info("Step 1/8: Chunking (%s strategy)...", self.config.chunking.strategy)
        chunks = self.chunker.chunk(document_text)
        logger.info("  → %d chunks produced.", len(chunks))

        if self.config.chunking.strategy == "propositional":
            logger.info("Step 2/8: Propositions already generated by propositional chunker.")
        else:
            logger.info("Step 2/8: Skipping proposition generation (strategy != propositional).")

        chunk_ids = self.writer.write_chunks(doc_id, chunks)

        logger.info("Step 3/8: Extracting entities & relations (parallel, concurrency=%d)...",
                     self.config.extraction.max_concurrency)
        extraction_results = await self.er_extractor.extract_from_chunks(chunks)
        total_entities = sum(len(r.entities) for r in extraction_results)
        total_relations = sum(len(r.relations) for r in extraction_results)
        logger.info("  → %d entities, %d relations extracted.", total_entities, total_relations)

        logger.info("Step 4/8: Writing entities & relations to Neo4j...")
        self.writer.write_entities_and_relations(chunk_ids, extraction_results)

        if self.config.entity_resolution.enabled:
            logger.info("Step 5/8: Entity Resolution (KNN → WCC → Word Distance → LLM)...")
            er_config = self.config.entity_resolution
            embedding_model = self.config.embedding.model

            async def embed_fn(texts: list[str]) -> list[list[float]]:
                return await hf_embed(texts, model_name=embedding_model, show_progress=True)

            resolver = EntityResolver(
                driver=self._driver,
                llm=self.llm,
                embedding_fn=embed_fn,
                k_neighbors=er_config.k_neighbors,
                similarity_threshold=er_config.similarity_threshold,
                word_distance_threshold=er_config.word_distance_threshold,
                max_concurrency=er_config.max_concurrency,
                database=self.config.neo4j.database,
                use_llm=er_config.use_llm,
            )
            decisions = await resolver.resolve()
            logger.info("  → %d merge groups resolved.", len(decisions))
        else:
            logger.info("Step 5/8: Entity resolution DISABLED — skipping.")

        algo = self.config.community_detection.algorithm
        logger.info("Step 6/8: Community detection (%s via Neo4j GDS)...", algo)
        detector = CommunityDetector(
            driver=self._driver,
            database=self.config.neo4j.database,
            algorithm=algo,
            resolution=self.config.community_detection.resolution,
            level=self.config.community_detection.level,
        )
        communities = detector.detect()
        logger.info("  → %d communities detected.", len(communities))

        logger.info("Step 7/8: Writing communities to Neo4j...")
        self.writer.write_communities(communities)

        logger.info("Step 8/8: Summarizing communities (parallel)...")
        summarizer = CommunitySummarizer(
            driver=self._driver,
            llm=self.llm,
            max_concurrency=self.config.extraction.max_concurrency,
            database=self.config.neo4j.database,
        )
        summaries = await summarizer.summarize(communities)
        self.writer.write_community_summaries(summaries)

        logger.info("=" * 60)
        logger.info("GraphRAG Pipeline COMPLETE")
        logger.info("=" * 60)

    def close(self) -> None:
        """Clean up resources."""
        self._driver.close()



def _read_document(path: str) -> str:
    """Read a document file. Supports .txt and .pdf."""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Document not found: {path}")

    if p.suffix.lower() == ".pdf":
        try:
            from PyPDF2 import PdfReader
            reader = PdfReader(str(p))
            return "\n".join(page.extract_text() or "" for page in reader.pages)
        except ImportError:
            raise ImportError("Install PyPDF2 to read PDF files: pip install PyPDF2")
    else:
        return p.read_text(encoding="utf-8")


async def async_main(config_path: Optional[str], document_paths: list[str]) -> None:
    config = load_config(config_path)
    pipeline = GraphRAGPipeline(config)

    try:
        for i, doc_path in enumerate(document_paths, 1):
            logger.info("=" * 60)
            logger.info("Processing document %d / %d: %s", i, len(document_paths), doc_path)
            logger.info("=" * 60)
            document_text = _read_document(doc_path)
            await pipeline.run(
                document_text=document_text,
                doc_title=Path(doc_path).stem,
                doc_source=doc_path,
            )
    finally:
        pipeline.close()


def _collect_documents(path: str) -> list[str]:
    """Collect document paths from a file or directory."""
    p = Path(path)
    if p.is_file():
        return [str(p)]
    elif p.is_dir():
        extensions = {".txt", ".pdf"}
        files = sorted(f for f in p.rglob("*") if f.suffix.lower() in extensions)
        if not files:
            raise FileNotFoundError(f"No .txt or .pdf files found in: {path}")
        logger.info("Found %d documents in %s", len(files), path)
        return [str(f) for f in files]
    else:
        raise FileNotFoundError(f"Path not found: {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Microsoft GraphRAG Pipeline (Neo4j Edition)")
    parser.add_argument("--config", type=str, default=None, help="Path to config.yaml")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--document", type=str, help="Path to a single document (.txt or .pdf)")
    group.add_argument("--directory", type=str, help="Path to a directory of documents (processes all .txt and .pdf files)")

    args = parser.parse_args()

    path = args.document or args.directory
    document_paths = _collect_documents(path)
    asyncio.run(async_main(args.config, document_paths))


if __name__ == "__main__":
    main()

